inherit_from: .rubocop_todo.yml
Documentation: 
  Enabled: false
EndOfLine:
  Enabled: false  
AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'